### ISSUE TITLE
Add ability to order items in descending order

### ISSUE THREAD

**Issue by droidchef** [lazysource/ireport#13]
This requires a Dropdown above the table next to the order by dropdown field. The ascending implementation is already there, we need to extend it to allow users to also do a descending order by for any options available.

**Comment by sahildua2305** [comment]
I have partially resolved this issue via https://github.com/lazysource/ireport/commit/9fd6112f4843a7739cb4b5bc43c3f0861a28de52.

Front end changes are pending, however.

**Comment by droidchef** [comment]
We can close this! And have the UI sorted separately.
