### ISSUE TITLE
Add a Violation Model

### ISSUE THREAD

**Issue by droidchef** [lazysource/ireport#3]
Abstract out a Violation class that would allow us to build sorting, ordering, grouping capabilities on top of it.

**Comment by droidchef** [comment]
Fixed!

**Comment by sahildua2305** [comment]
Do mention the issue number in commit, so that it's easy to see changes that closed this issue.

**Comment by droidchef** [comment]
I did :( for some reason it didn't show up here.

See this https://github.com/lazysource/ireport/commit/3c4072745ce5c65bded2b5a34c1b15efd383db4b

**Comment by sahildua2305** [comment]
I think you will have to mention the issue number separated by a space. Like this:
`Fixes issue #3; bla bla`

**Comment by droidchef** [comment]
Alright! Noted! ;)

**Comment by manrajgrover** [comment]
Recently Github had added a feature that if you add commit message as `Fixes issue #3` and you have commit access to repo, it will automatically close the issue.

**Comment by sahildua2305** [comment]
Yep! Even `Fixes #3` works :smile:

**Comment by droidchef** [comment]
So the crux is! I need to add a space!
