### ISSUE TITLE
Enable persistent storage

### ISSUE THREAD

**Issue by sahildua2305** [lazysource/ireport#7]
Enable persistent storage to show the last opened file report (parsed) on start.

**Comment by droidchef** [comment]
This might be of some help 

http://www.mylifeforthecode.com/saving-and-restoring-window-state-in-electron/

**Comment by droidchef** [comment]
Have a key called `lastViewedReportPath` and store the value in it, whenever the app opens, the `defaultPath` should point to `lastViewedReportPath` if at all it exists in the local storage.

**Comment by sahildua2305** [comment]
I think this - https://github.com/jviotti/electron-json-storage will serve the purpose. Will have a look at both though.
